image: python:3

lint:
 stage: test
 script:
 - pip install yapf
 - yapf --recursive --style google .
 only:
 - pushes

unittest:
 stage: test
 needs:
  - pipeline: test
    job: lint
 script:
  - pip install -r requirements.txt
  - pytest
 only:
  - pushes
